version: 2.1

executors:
  amd64-executor:
    docker:
      - image: circleci/python:3.12  # Use CircleCI's Docker image for amd64 builds

  arm64-executor:
    machine:
      resource_class: arm.medium  # Use the correct resource class for ARM64

jobs:
  build_amd64:
    docker:
      - image: circleci/python:3.12
    parameters:
      base_version:
        type: string
    steps:
      - checkout
      - setup_remote_docker  # Only needed for Docker executor

      - run:
          name: Build Docker Image for AMD64
          command: |
            BASE_IMAGE_TYPE=$(echo "<< parameters.base_version >>" | cut -d'-' -f1)
            BASE_IMAGE_VERSION=$(echo "<< parameters.base_version >>" | cut -d'-' -f2)
            DOCKERFILE_DIR="${BASE_IMAGE_TYPE}"
            IMAGE_BASE_NAME="test-build"
            OVERALL_TAG="3.12-<< parameters.base_version >>"
            MAIN_TAG="${IMAGE_BASE_NAME}:${OVERALL_TAG}"

            # Build the image
            docker buildx build --platform linux/amd64 --tag $MAIN_TAG \
              --build-arg PYTHON_VERSION=3.12 \
              --build-arg BASE_IMAGE_VERSION=${BASE_IMAGE_VERSION} \
              -f ${DOCKERFILE_DIR}/Dockerfile .

  build_arm64:
    machine:
      resource_class: arm.medium  # Use the correct resource class for ARM64
    parameters:
      base_version:
        type: string
    steps:
      - checkout

      - run:
          name: Build Docker Image for ARM64
          command: |
            BASE_IMAGE_TYPE=$(echo "<< parameters.base_version >>" | cut -d'-' -f1)
            BASE_IMAGE_VERSION=$(echo "<< parameters.base_version >>" | cut -d'-' -f2)
            DOCKERFILE_DIR="${BASE_IMAGE_TYPE}"
            IMAGE_BASE_NAME="test-build"
            OVERALL_TAG="3.12-<< parameters.base_version >>"
            MAIN_TAG="${IMAGE_BASE_NAME}:${OVERALL_TAG}"

            # Build the image
            docker buildx build --platform linux/arm64 --tag $MAIN_TAG \
              --build-arg PYTHON_VERSION=3.12 \
              --build-arg BASE_IMAGE_VERSION=${BASE_IMAGE_VERSION} \
              -f ${DOCKERFILE_DIR}/Dockerfile .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_amd64:
          name: Build Alpine AMD64
          base_version: alpine-3.19

      - build_arm64:
          name: Build Alpine ARM64
          base_version: alpine-3.19

      - build_amd64:
          name: Build Ubuntu AMD64
          base_version: ubuntu-22.04

      - build_arm64:
          name: Build Ubuntu ARM64
          base_version: ubuntu-22.04
          
