version: 2.1

executors:
  amd64-executor:
    docker:
      - image: circleci/python:3.12  # Use CircleCI's Docker image for amd64 builds

  arm64-executor:
    machine:
      image: ubuntu-2004:2022.04  # Use machine executor for ARM64 builds (native ARM instances)

jobs:
  build:
    parameters:
      platform:
        type: string
      base_version:
        type: string

    executor: "<< parameters.platform >>"  # This will dynamically choose between amd64 or arm64

    steps:
      - checkout

      - setup_remote_docker  # Required to use Docker in CircleCI

      - run:
          name: Build Docker Image
          command: |
            BASE_IMAGE_TYPE=$(echo "<< parameters.base_version >>" | cut -d'-' -f1)
            BASE_IMAGE_VERSION=$(echo "<< parameters.base_version >>" | cut -d'-' -f2)
            DOCKERFILE_DIR="${BASE_IMAGE_TYPE}"
            IMAGE_BASE_NAME="test-build"
            OVERALL_TAG="3.12-<< parameters.base_version >>"
            MAIN_TAG="${IMAGE_BASE_NAME}:${OVERALL_TAG}"

            # Build the image (no push to Docker Hub)
            docker buildx build --platform << parameters.platform >> --tag $MAIN_TAG \
              --build-arg PYTHON_VERSION=3.12 \
              --build-arg BASE_IMAGE_VERSION=${BASE_IMAGE_VERSION} \
              -f ${DOCKERFILE_DIR}/Dockerfile .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          name: Build Alpine AMD64
          platform: amd64-executor
          base_version: alpine-3.19

      - build:
          name: Build Alpine ARM64
          platform: arm64-executor
          base_version: alpine-3.19

      - build:
          name: Build Ubuntu AMD64
          platform: amd64-executor
          base_version: ubuntu-22.04

      - build:
          name: Build Ubuntu ARM64
          platform: arm64-executor
          base_version: ubuntu-22.04
