name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "*"

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.12"]
        # base_version: ["alpine-3.19", "ubuntu-22.04"]
        base_version: ["ubuntu-22.04"] # for faster testing, only build ubuntu
        platform: ["linux/amd64", "linux/arm64"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create a new builder
        run: docker buildx create --use --name mybuilder

      - name: Build and push Docker image
        run: |
          # Calculate the base image type and version
          BASE_IMAGE_TYPE=$(echo "${{ matrix.base_version }}" | cut -d'-' -f1)
          BASE_IMAGE_VERSION=$(echo "${{ matrix.base_version }}" | cut -d'-' -f2)
          DOCKERFILE_DIR="${BASE_IMAGE_TYPE}"
          PROJECT_NAME="${GITHUB_REPOSITORY#*/}"
          IMAGE_BASE_NAME="${DOCKER_HUB_USERNAME}/${PROJECT_NAME}"
          OVERALL_TAG="${{ matrix.python_version }}-${{ matrix.base_version }}"
          MAIN_TAG="${IMAGE_BASE_NAME}:${OVERALL_TAG}"

          # Tag 'latest' only for Alpine builds
          if [[ "${{ matrix.base_version }}" == "alpine-"* ]]; then
            LATEST_TAG="${IMAGE_BASE_NAME}:latest-github"
            echo "Building and pushing tags: $MAIN_TAG and $LATEST_TAG"
            docker buildx build --push \
              --tag $MAIN_TAG --tag $LATEST_TAG --platform ${{ matrix.platform }} \
              --build-arg PYTHON_VERSION=${{ matrix.python_version }} \
              --build-arg BASE_IMAGE_VERSION=${BASE_IMAGE_VERSION} \
              -f ${DOCKERFILE_DIR}/Dockerfile \
              .
          else
            echo "Building and pushing tag: $MAIN_TAG"
            docker buildx build --push \
              --tag $MAIN_TAG --platform ${{ matrix.platform }} \
              --build-arg PYTHON_VERSION=${{ matrix.python_version }} \
              --build-arg BASE_IMAGE_VERSION=${BASE_IMAGE_VERSION} \
              -f ${DOCKERFILE_DIR}/Dockerfile \
              .

          fi
          # Wait a few seconds to ensure the image is pushed to Docker Hub
          echo "Waiting for Docker Hub to register the image..."
          sleep 10

          # Retry logic for inspecting the image digest
          retries=5
          while [ $retries -gt 0 ]; do
              digest=$(docker inspect --format='{{index .RepoDigests 0}}' ${MAIN_TAG} | cut -d'@' -f2)
              if [ -n "$digest" ]; then
                  echo "$digest" > digest-${{ matrix.platform }}.txt
                  break
              fi
              echo "Retrying digest retrieval in 10 seconds..."
              sleep 10
              retries=$((retries - 1))
          done

      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digest-${{ matrix.platform }}
          path: digest-${{ matrix.platform }}.txt

  # This second job combines the images into a multi-platform manifest
  create-manifest:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.12"]
        base_version: ["alpine-3.19", "ubuntu-22.04"]
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download digests for amd64
        uses: actions/download-artifact@v3
        with:
          name: digest-linux/amd64
          path: .
      - name: Download digests for arm64
        uses: actions/download-artifact@v3
        with:
          name: digest-linux/arm64
          path: .

      - name: Create and push multi-platform manifest
        run: |
          BASE_IMAGE_TYPE=$(echo "${{ matrix.base_version }}" | cut -d'-' -f1)
          PROJECT_NAME="${GITHUB_REPOSITORY#*/}"
          IMAGE_BASE_NAME="${DOCKER_HUB_USERNAME}/${PROJECT_NAME}"
          OVERALL_TAG="${{ matrix.python_version }}-${{ matrix.base_version }}"
          MAIN_TAG="${IMAGE_BASE_NAME}:${OVERALL_TAG}"

          # Read the digests from files
          digest_amd64=$(cat digest-linux/amd64.txt)
          digest_arm64=$(cat digest-linux/arm64.txt)

          # Combine the platforms into a manifest for each base image
          docker buildx imagetools create --tag $MAIN_TAG \
            ${IMAGE_BASE_NAME}:${OVERALL_TAG}@${digest_amd64} \
            ${IMAGE_BASE_NAME}:${OVERALL_TAG}@${digest_arm64}

          # Only create the 'latest' tag for Alpine builds
          if [[ "${{ matrix.base_version }}" == "alpine-"* ]]; then
            LATEST_TAG="${IMAGE_BASE_NAME}:latest-github"
            docker buildx imagetools create --tag $LATEST_TAG \
              ${IMAGE_BASE_NAME}:${OVERALL_TAG}@${digest_amd64} \
              ${IMAGE_BASE_NAME}:${OVERALL_TAG}@${digest_arm64}
          fi

# End of file