name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.12']
        alpine_version: ['3.19']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ env.DOCKER_HUB_TOKEN }}" | docker login -u "${{ env.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          PROJECT_NAME="${GITHUB_REPOSITORY#*/}"
          COMMIT_HASH_SHORT=$(echo "${{ github.sha }}" | cut -c1-7)
          IMAGE_BASE_NAME="${DOCKER_HUB_USERNAME}/${PROJECT_NAME}"
          echo "IMAGE_BASE_NAME=${IMAGE_BASE_NAME}"
          # Correct way to handle tag concatenation
          PYTHON_ALPINE_TAG="${{ matrix.python_version }}-alpine${{ matrix.alpine_version }}"
          TAGS="${IMAGE_BASE_NAME}:${PYTHON_ALPINE_TAG}"
          echo "Building and pushing tags: $TAGS"
          docker buildx build --push \
            --tag $TAGS \
            --platform linux/amd64,linux/arm64 \
            --build-arg PYTHON_VERSION=${{ matrix.python_version }} \
            --build-arg ALPINE_VERSION=${{ matrix.alpine_version }} \
            .